version: 0.2
phases:
  build:
    commands:
      - echo "Test Code..."
      - mvn test
  post_build:
    commands:
      - echo "Starting build..."
      - mvn package
artifacts:
  files:
    - '**/*' 
  base-directory: target
  discard-paths: yes
