version: 0.2

phases:
  install:
    
    commands:
      - yum update -y
      - yum install -y python3 python3-pip
      - python3 -m pip install urllib3==1.26.15
      - python3 -m pip install aws-sam-cli
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region $AWS_DEFAULT_REGION
      
  build:
    commands:
      - sam --version
      - sam build --template-file template.yaml
      - sam package --template-file template.yaml --output-template-file packaged.yaml  
      - sam deploy  --template-file /codebuild/output/src851451288/src/github.com/sudeshmane/AwsRepo/packaged.yaml --resolve-s3 s3://manesudesh-c-formation  --stack-name sam-stack-app-8
     
      
  build:
    commands:
      - echo "Test Code..."
      - mvn test
  post_build:
    commands:
      - echo "Starting build..."
      - mvn package
      - sam package --template-file template.yaml --output-template-file packaged.yaml 
artifacts:
  files:
    - '**/*.jar' 
  base-directory: target
  discard-paths: yes
secondary-artifacts:
  secondary-artifact-1:
    files:
      - '**/*packaged.yaml' 
    name: another-artifact
