version: 0.2
phases:
  build:
    commands:
      - echo "Test Code..."
      - mvn test
  post_build:
    commands:
      - echo "Starting build..."
      - mvn package
      - sam package --template-file template.yaml --output-template-file packaged.yaml 
artifacts:
  files:
    - '**/*.jar' 
  base-directory: target
  discard-paths: yes
